### ISSUE TITLE
Designing the Register Form

### ISSUE THREAD

**Issue by tharushi08** [PixelCtrl/CtrlTangle-CloudLogin#1]
**- Task 01**

- [x]  Create the Register Form
- [x]  Create the Login Form
- [x] Completing the UI Designs

**Comment by tharushi08** [comment]
All the UI Screens Related to Registration & Login is Completed.
